# Header
menu:
  Home: https://zchen11611.github.io
  Project: /Project.html
  Weekly Reports: /Weekly_Reports.html
  Github: https://github.com/zchen11611/EE629

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: images/favicon
twitter:
google_plus:
fb_admins:
fb_app_id:

stylus:
  compress: false
